/*
 * Copyright 2024 SiriusXM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package snapshot4s.my_project

import snapshot4s.{Path, SnapshotConfig}

/* This file is autogenerated when using the sxm-snapshot4s SBT
 * plugin. We do not depend on the plugin in the docs build, so must
 * write it manually. */

object generated:

  implicit val snapshotConfig: SnapshotConfig = SnapshotConfig(
    resourceDirectory = Path("non-existent-path"),
    outputDirectory = Path("non-existent-path"),
    sourceDirectory = Path("non-existent-path")
  )
