addDependencyTreePlugin

addSbtPlugin("org.scalameta"     % "sbt-scalafmt"              % "2.5.2")
addSbtPlugin("org.scalameta"     % "sbt-mdoc"                  % "2.5.2")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"               % "0.6.4")
addSbtPlugin("com.github.cb372"  % "sbt-explicit-dependencies" % "0.3.1")
addSbtPlugin("org.typelevel"     % "sbt-typelevel-no-publish"  % "0.7.1")
addSbtPlugin("org.typelevel"     % "sbt-typelevel-mima"        % "0.7.1")
addSbtPlugin("org.typelevel"     % "sbt-typelevel-versioning"  % "0.7.1")
addSbtPlugin("org.typelevel"     % "sbt-typelevel-scalafix"    % "0.7.1")
addSbtPlugin("org.typelevel"     % "sbt-typelevel-settings"    % "0.7.1")
addSbtPlugin("org.typelevel"     % "sbt-typelevel-ci-release"  % "0.7.1")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"             % "0.12.0")
addSbtPlugin("com.eed3si9n"      % "sbt-projectmatrix"         % "0.10.0")
addSbtPlugin("org.scala-js"      % "sbt-scalajs"               % "1.16.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"                % "5.10.0")
